# Generated by Django 4.2.16 on 2026-07-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdviceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_excerpt", models.TextField(blank=True)),
                ("response_text", models.TextField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("fallback", "降级"),
                            ("failed", "失败"),
                        ],
                        default="fallback",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advice",
                        to="diagnosis.detectionrecord",
                    ),
                ),
            ],
            options={
                "db_table": "ai_analysis_advicerecord",
            },
        ),
    ]
