# Generated by Django 4.2.16 on 2026-07-15 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(upload_to="detections/originals/%Y/%m/%d"),
                ),
                (
                    "visualized_image",
                    models.ImageField(
                        blank=True, upload_to="detections/visuals/%Y/%m/%d"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("image_width", models.PositiveIntegerField(default=0)),
                ("image_height", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "backend",
                    models.CharField(
                        choices=[("mock", "Mock"), ("ultralytics", "Ultralytics")],
                        default="mock",
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(default="v1", max_length=50)),
                ("weights_path", models.CharField(blank=True, max_length=255)),
                ("class_names", models.JSONField(blank=True, default=list)),
                ("confidence_threshold", models.FloatField(default=0.25)),
                ("input_size", models.PositiveIntegerField(default=640)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("xmin", models.FloatField()),
                ("ymin", models.FloatField()),
                ("xmax", models.FloatField()),
                ("ymax", models.FloatField()),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="diagnosis.detectionrecord",
                    ),
                ),
            ],
        ),
    ]
