# Generated by Django 4.2.27 on 2026-07-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='original_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='detectionrecord',
            name='visualized_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
