# Generated by Django 4.2.27 on 2026-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_detectionrecord_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='backend',
            field=models.CharField(choices=[('mock', 'Mock'), ('onnx', 'ONNX'), ('ultralytics', 'Ultralytics')], default='mock', max_length=32),
        ),
        migrations.AddIndex(
            model_name='detectionrecord',
            index=models.Index(fields=['-created_at'], name='diag_record_created_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionrecord',
            index=models.Index(fields=['user', '-created_at'], name='diag_record_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionrecord',
            index=models.Index(fields=['status', '-created_at'], name='diag_record_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['label'], name='diag_result_label_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['record', 'label'], name='diag_result_record_label_idx'),
        ),
    ]
